# Setup
title:               'Vedang Asgaonkar'
tagline:             'At the curtain of the waterfall'
description:         'Third year undergrad at CSE, IIT Bombay'
url:                 http://vedangasgaonkar.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              'Vedang Asgaonkar'
  url:               https://github.com/VedangAsgaonkar/
  email:             vedang@cse.iitb.ac.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
